Bugfix/vulnerabilities 2.9
smartdevicelink/sdl_server pull request #206
Opened 2020-09-24 17:46 UTC by crokita

This PR is ready for review.

### Risk
This PR makes no API changes.

### Summary
There are major version updates for some of the dependent packages. Bootstrap related libraries are updated and a couple of tweaks are made to the UI to fix a couple of quirks with the major version change for the front end libraries. 

In addition, a new set of packages are used for the updated build process, viewable in the package.json file. The vue cli program is used to set up the new build environment for the policy server, and all needed content has been moved over. Two updates to be compatible with the new build is updating how the policy server works with the Vue dev server (in dev mode the policy server will use the dev server and only attach routes it needs), and also updating how the AUTH_TYPE variable is passed to the front end from the server (vue cli allows this through VUE_APP environment variables). Integration with the dev server and passing of the AUTH_TYPE variable happens in `vue.config.js` and in `public/index.html`. 

Existing package json scripts should still work and have been updated to use the new vue cli commands. Hot reloading will work in dev mode and the policy server will still serve the generated built files in production mode.

##### Enhancements
The new build comes with a linter program, which runs when starting the policy server and via `npm run lint`. The policy server currently has linter issues to work through which will be addressed in a future PR. Errors will happen once when attempting to run the server, but it can be ignored by running the command again.

2020-09-25 20:47 UTC, renonick87 requested changes
The UI is currently unusable with these changes. Opening any page in a browser results in the page being constantly refreshed at a rate too fast for the content being displayed to actually be updated.

2020-09-29 20:24 UTC, crokita commented
There was an issue with enabling basic password authentication where the auth type wasn't correctly passed to the Vue router instance, which caused the infinite refresh issue. That has now been resolved.

2020-09-30 18:23 UTC, renonick87 requested changes
Below is a list of UI bugs that appear to have been added. Any issues that were found to be browser-specific are labeled as such. For any uncertainty as to the expected results of some scenarios, check the testing server on the ec2 instance.
- Creating/Editing functional group - The text list of Special Grants appears more faded and almost looks like it shouldn't be edited which could be confusing. Additionally, each list item cuts off the checkbox of the previous item in the list.
- App Details Page - When clicking the `Automatically approve future versions of this app` toggle, a window appears to confirm this decision. Selecting `confirm` updates the toggle and saves the update. Selecting `cancel` will not save the update, but will still cause the toggle to visually update (refreshing the page reverts it to its last saved value).
- Creating/editing custom vehicle data - `Is Mandatory`, its checkbox, and its description all appear to be at slightly different levels with one another.
- Tab window icon (Chrome-specific) - The icon that appears on the tab is the Vue logo found at `public/favicon.ico` but it should use the SDL logo at `src/assets/images/favicon.ico`.

Below are issues that occur when running the dev server via `npm start`.
- Module_config page - Integer input blocks for Policy Table refresh fields and Notification rates do not appear and are not editable as a result. 
- Generate Certificate modal - Input fields do not appear and are not editable.
- `Generate Key and Certificate` buttons are white and darken when hovered over. They should be grey and lighten when hovered over. The exact coloring is a pretty minor issue but currently it doesn't really look like it's a button.

2020-10-05 18:03 UTC, renonick87 approved these changes

2020-10-05 19:24 UTC, merged