Feature/docker environment
smartdevicelink/sdl_server pull request #278
Opened 2022-01-28 21:54 UTC by crokita

Fixes #277 

Depends on #275. Review should wait until merged. 

This PR is ready for review.

### Risk
This PR makes no API changes.

### Summary
Adds a new docker folder to the project, where everything can be run in a Docker container environment. Provided are instructions on how to run the environment and some environment variables to be conscious of. WebEngine support, Redis caching and certification generation are all possible.

For this PR review the line in `docker-compose.yml` that specifies the argument for what VERSION the policy server runs on should change to `develop` to bring in the recent required changes for the server to function in docker mode:

```
    build:
      context: .
      args:
        - VERSION=develop
```

2022-02-03 21:52 UTC, renonick87 requested changes
See feedback.

2022-02-04 18:12 UTC, crokita commented on docker/Dockerfile
> +ARG VERSION=master
The docker-compose.yml file has priority in the VERSION that is set. It replaces the VERSION in the Dockerfile.

2022-02-10 22:19 UTC, renonick87 commented on docker/docker-compose.yml
> +      CACHE_HOST: "${CACHE_HOST:-redis}"
Is there any reason not to use predefined values for the CACHE variables like with the DB_HOST? I would think that any other values wouldn't be able to connect to the redis instance.

2022-02-15 15:46 UTC, crokita commented on docker/docker-compose.yml
> +      CACHE_HOST: "${CACHE_HOST:-redis}"
Agreed. Hardcoded the redis values here

2022-02-15 21:39 UTC, renonick87 approved these changes

2022-02-16 15:10 UTC, merged